config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:show, :new, :create] do
    resources :subs, only: [:new]
  end

  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: [:destroy, :new] do
    resources :posts, only: [:new]
  end

  resources :posts, except: [:destroy, :new, :index]


end

app/models/post.rb
class Post < ActiveRecord::Base

  validates :title, :subs, :author, presence: true

  belongs_to(
    :author,
    class_name: "User",
    foreign_key: :author_id
  )

  has_many(
    :post_subs,
    inverse_of: :post,
    dependent: :destroy,
    class_name: "PostSub",
    foreign_key: :post_id
  )

  has_many :subs, :through => :post_subs, source: :sub

end

app/models/post_sub.rb
class PostSub < ActiveRecord::Base

  validates :sub, :post, presence: true

  belongs_to(
    :sub,
    class_name: "Sub",
    foreign_key: :sub_id
  )

  belongs_to(
    :post,
    class_name: "Post",
    foreign_key: :post_id
  )
end

app/models/sub.rb
class Sub < ActiveRecord::Base

  validates :title, :moderator, presence: true

  belongs_to(
    :moderator,
    class_name: "User",
    foreign_key: :moderator_id,
  )

  has_many :posts, :through => :post_subs, source: :post

  has_many :post_subs, inverse_of: :sub, dependent: :destroy

end

app/models/user.rb
class User < ActiveRecord::Base

  validates :email, :password_digest, :session_token, :username, presence: true
  validates :username, :session_token, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil if user.nil?

    if user.is_password?(password)
      user
    else
      nil
    end
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def password
    @password
  end

  def password_digest
    BCrypt::Password.new(super)
  end

  def is_password?(password)
    self.password_digest.is_password?(password)
  end

  def generate_session_token
    SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = generate_session_token
    save!
  end

  private

    def ensure_session_token
      self.session_token ||= generate_session_token
    end

end

app/controllers/application_controller.rb
require 'byebug'

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  def current_user
    return nil if session[:session_token].nil?

    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def sign_in(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
    @current_user = user
  end

  def sign_out!
    @current_user && @current_user.reset_session_token!
    session[:session_token] = nil
  end

  def signed_in?
    !!current_user
  end

  private

    def ensure_signed_in
      redirect_to new_user_url unless signed_in?
    end

end

app/controllers/posts_controller.rb
require 'byebug'
class PostsController < ApplicationController

  before_action :ensure_only_authors_can_edit_posts, only: [:edit, :update]

  def show
    @post = Post.includes(:author).find(params[:id])
    render :show
  end

  def new
    @post = Post.new
    @sub = Sub.find(params[:sub_id])
    @subs = Sub.all
    render :new
  end

  def create
    @post = Post.new(post_params.merge(author_id: current_user.id))
    # debugger
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      redirect_to sub_url(post_params[:sub_id])
    end
  end

  def edit
    @sub = Sub.new
    @subs = Sub.all
    render :edit
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  private

    def post_params
      params.require(:post).permit(:title, :url, :content, :sub_ids => [])
    end

    def ensure_only_authors_can_edit_posts
      @post = Post.find(params[:id])
      redirect_to post_url(@post) unless current_user.id == @post.author_id
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password])

    unless @user.nil?
      sign_in(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = user.errors.full_messages
      render :new
    end
  end

  def destroy
    sign_out!

    redirect_to new_session_url
  end

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_action :ensure_only_moderators_can_edit_subs, only: [:edit, :update]

  def show
    @sub = Sub.includes(:posts => :author).find(params[:id])
    render :show
  end

  def index
    @subs = Sub.all

    render :index
  end

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_params.merge(moderator_id: current_user.id))

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    render :edit
  end

  def update
    @sub = Sub.find(params[:id])

    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  private

    def sub_params
      params.require(:sub).permit(:title, :description)
    end

    def ensure_only_moderators_can_edit_subs
      @sub = Sub.find(params[:id])
      redirect_to sub_url(@sub) unless current_user.id == @sub.moderator_id
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :ensure_signed_in, only: [:show]

  def show
    @user = User.find(params[:id])
    render :show
  end

  def new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

    def user_params
      params.require(:user).permit(:email, :username, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dreddit</title>

  <%= csrf_meta_tags %>
</head>
<body>

<%= render "shared/errors" %>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<% if post.persisted? %>
  <% action, value = post_url, "PATCH" %>
<% else %>
  <% action, value = posts_url, "POST"  %>
<% end %>



<form action="<%= action %>" method="POST">

  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  </input>

  <input
    type="hidden"
    name="_method"
    value="<%= value %>">
  </input>

  <% @subs.each do |subdreddit| %>
    <label>
      <%= subdreddit.title %>
      <input
        type="checkbox"
        name="post[sub_ids][]"
        value="<%= subdreddit.id %>"
        <%="checked" if ( sub.title == subdreddit.title || post.subs.include?(subdreddit.title) )%>>
      </input>
    </label>
    <br>
  <% end %>


  <% unless post.persisted? %>
    <label>
      Title:
      <input
        type="text"
        name="post[title]"
        placeholder="Check out this cool cat.">
      </input>
    </label>
    <br>

    <label>
      URL (optional):
      <input
        type="text"
        name="post[url]"
        placeholder="http://lmgtfy.com/">
      </input>
    </label>
    <br>
    <br>
  <% end %>

  <label>
    Content
    <textarea
      name="post[content]"
      placeholder="Add your thoughts..."><%= post.content %></textarea>
  <label>

  <button>Submit</button>

</form>

app/views/posts/edit.html.erb
<h1> Edit <%= @post.title %> </h1>

<%= render "form", post: @post, sub: @sub %>

app/views/posts/new.html.erb
<h1> New Post </h1>

<%= render "form", post: @post, sub: @sub %>

app/views/posts/show.html.erb
<h1> <a href="<%= @post.url %>"> <%= @post.title %> </a> </h1>

<% if @post.author_id == current_user.id %>
  <a href="<%= edit_post_url(@post) %>">
    Edit Post
  </a>
<% end %>

<p><%= @post.content %></p>
<br>
<br>

app/views/shared/_errors.html.erb
<% if flash.now[:errors] %>
  <%= flash.now[:errors] %>
<% end %>

app/views/shared/_signin.html.erb
<form action="<%= session_url %>" method="POST">

  <input
    type="hidden"
    name="_method"
    value="DELETE">
  </input>

  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  </input>

  <button>Sign Out</button>

</form>

app/views/subs/_form.html.erb
<% if sub.persisted? %>
  <% value, action = "PATCH", sub_url(sub.id) %>
<% else %>
  <% value, action = "POST", subs_url %>
<% end %>

<form action="<%= action %>" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  </input>

  <input
    type="hidden"
    name="_method"
    value="<%= value %>">
  </input>



  <label>
    Title:
    <input
      type="text"
      name="sub[title]"
      placeholder="cats"
      value="<%= sub.title %>">
    </input>
  </label>
  <br>
  <br>

  <label>
    Description
    <textarea
      name="sub[description]"
      placeholder="Give a short description about your subdreddit!"><%= sub.description %></textarea>
  </label>
  <br>
  <br>

  <button>Submit</button>

</form>

app/views/subs/edit.html.erb
<h1>Edit the Sub</h1>

<%= render "form", sub: @sub %>

app/views/subs/index.html.erb
<h1>List of Subs</h1>

<ul>
  <% @subs.each do |sub| %>
    <a href="<%= sub_url(sub) %>">
      <p><%= sub.title %> -- <%= sub.description %>
      </p>
    </a>
  <% end %>
</ul>
<br>

<a href="<%= new_user_sub_url(current_user) %>">Create a SubDreddit</a>

app/views/subs/new.html.erb
<h1> Create New Subreddit </h1>

<%= render "form", sub: @sub %>

app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>

<% if current_user.id == @sub.moderator_id %>
  <a href="<%= edit_sub_url(@sub) %>">Edit Sub</a>
  <br>
  <br>
<% end %>

<label>
  Posts:
  <ul>
    <% @sub.posts.to_a.sort_by! { |post| post.created_at }.reverse.each do |post| %>
      <li>
        <a href="<%= (post.url.nil? || post.url.empty?) ? post_url(post) : post.url %>">
          <%= post.title %></a> --
            <a href="<%= post_url(post) %>">discussion</a> -- Created by: <%= post.author.username %>
      </li>

    <% end %>
  </ul>
</label>

<a href="<%= new_sub_post_url(@sub.id) %>">Add New Post</a>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="POST">

  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  </input>

  <label>
    Email:
    <input
      type="text"
      name="user[email]">
    </input>
  </label>
  <br>

  <label>
    Username:
    <input
      type="text"
      name="user[username]">
    </input>
  </label>
  <br>

  <label>
    Password:
    <input
      type="password"
      name="user[password]">
    </input>
  </label>
  <br>

  <button>Submit</button>

</form>

app/views/users/show.html.erb
<h1> <%= @user.username %>'s Profile Page </h1>

<form action="<%= session_url %>" method="POST">

  <input
    type="hidden"
    name="_method"
    value="DELETE">
  </input>

  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  </input>

  <button>Sign Out</button>

</form>
<br>
<br>

<a href="<%= new_user_sub_url(@user) %>">Create a SubDreddit</a>